### PR TITLE
refactor: move `testdata` from `pkg` to `testutil`

### PR DESCRIPTION
**Pull request by jasonmokk**
# Description

This PR moves the `testdata` package from `pkg` into `testutil` since it is a test-related package.

Closes: #2292 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Include instructions and any relevant details so others can reproduce. 

- [ ] Tested CCTX in localnet
- [x] Tested in development environment
- [x] Go unit tests
- [x] Go integration tests
- [ ] Tested via GitHub Actions 

# Checklist:

- [ ] I have added unit tests that prove my fix feature works

### CODE REVIEW

**Review by lumtis — APPROVED** [review]
LGTM
Thanks for the contribution!

Note @jasonmokk : would be good to ask on the issue first to be assigned to it. We generally assign issue for interested contributors, this is to ensure people are not working simultaneously on the same thing

**Review by lumtis — CHANGES_REQUESTED** [review]
@jasonmokk seems like there are some tests with the location not updated: https://github.com/zeta-chain/node/actions/runs/9347664708/job/25725129231?pr=2296

**Comment by jasonmokk** [comment]
> @jasonmokk seems like there are some tests with the location not updated: [zeta-chain/node/actions/runs/9347664708/job/25725129231?pr=2296](https://github.com/zeta-chain/node/actions/runs/9347664708/job/25725129231?pr=2296)

Thanks for the feedback, I've corrected the pathname in the failing tests.

**Review by lumtis — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
