### PR TITLE
feat: cosmos sdk 0.47.10 upgrade

### PR DESCRIPTION
**Pull request by skosito**
# Description

Contains changes from these PRs:
https://github.com/zeta-chain/node/pull/2039
https://github.com/zeta-chain/node/pull/2014

One more PR left: https://github.com/zeta-chain/node/pull/2094 to remove tendermint dependency completely

Closes: #1928 

@lumtis @kingpinXD since you reviewed original PRs, only changes here are:
- fixing of unit test: https://github.com/zeta-chain/node/pull/2100/commits/70ceefabde127d67b4a4f72ae9be7f7d647ad7e1 to remove observer params

- make generate didnt work properly when running  in github actions with new docker setup for proto-gen, please check changes with `make generate-ci`, i noticed other projects used same workaround

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Include instructions and any relevant details so others can reproduce. 

- [ ] Tested CCTX in localnet
- [ ] Tested in development environment
- [ ] Go unit tests
- [ ] Go integration tests
- [ ] Tested via GitHub Actions 

# Checklist:

- [ ] I have added unit tests that prove my fix feature works

### CODE REVIEW

**Review by lumtis — APPROVED** [review]

**Comment by lumtis** [comment]
>make generate didnt work properly when running in github actions with new docker setup for proto-gen, please check changes with make generate-ci, i noticed other projects used same workaround

These are the modifications? (looking at the entire diff is buggy to me because of the PR size)
[0375c80](https://github.com/zeta-chain/node/pull/2100/commits/0375c804c3e14276948a18a058e099c89b335e22)
[aa43519](https://github.com/zeta-chain/node/pull/2100/commits/aa4351930ddb465729e6ce36e3971fe3df2315dc)

@gartnera maybe you can help on this one? 👀

**Comment by gartnera** [comment]
> @gartnera maybe you can help on this one? 👀

yep I'll take a look

proto-format needs a run it seems?

```
➜  node git:(feat-cosmos-sdk-0.47.10-upgrade) make proto-format
➜  node git:(feat-cosmos-sdk-0.47.10-upgrade) ✗ git diff --stat | cat
 proto/zetachain/zetacore/crosschain/genesis.proto  |  2 +-
 proto/zetachain/zetacore/crosschain/query.proto    | 22 +++++++++++-----------
 .../zetacore/crosschain/rate_limiter_flags.proto   |  2 +-
 proto/zetachain/zetacore/crosschain/tx.proto       |  8 +++++---
 proto/zetachain/zetacore/emissions/query.proto     |  7 +++----
 proto/zetachain/zetacore/emissions/tx.proto        |  2 +-
 proto/zetachain/zetacore/pkg/chains/chains.proto   | 17 ++++++++++-------
 7 files changed, 32 insertions(+), 28 deletions(-)
 ```

**Comment by gartnera** [comment]
> github.com/zetachain/zetacore/* was not generated in project folder, i guess {{github.workspace}}, what should happen when protoc gen script is run, without using root user, maybe there is better way, but this works

Yes I will look into that too

**Comment by gartnera** [comment]
> make generate didnt work properly when running in github actions with new docker setup for proto-gen, please check changes with make generate-ci, i noticed other projects used same workaround

should be resolved now by:
- set user and group of docker container to match host. this ensures file permissions are correct on both sides
- set buf cache directory. if the host user uid/gid doesn't exist inside the container, there will be no `$HOME/.cache` directory.

**Pull request merged**
