### PR TITLE
fix: check crosschain flags to stop inbound/outbound; get rid of outtx tracker iteration timeout

### PR DESCRIPTION
**Pull request by ws4charlie**
# Description

- Zetaclient will check crosschain flags to stop inbound/outbound txs (both EVM chain and Bitcoin):
     - [x] stop EVM/BTC intx observation and intx tracker processing.
     - [x] stop EVM/BTC outtx keysign.
     - [x] stop EVMBTC outtx tracker processing.
- Removed the timeout logic when iterating thru EVM chain outtx trackers.
- Unified logic of the method `WatchGasPrice` for EVM chain and Bitcoin chain.

Closes: [1888](https://github.com/zeta-chain/node/issues/1888), [1970](https://github.com/zeta-chain/node/issues/1970)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Include instructions and any relevant details so others can reproduce. 

- [ ] Tested CCTX in localnet
- [ ] Tested in development environment
- [ ] Go unit tests
- [ ] Go integration tests
- [ ] Tested via GitHub Actions 

# Checklist:

- [ ] I have added unit tests that prove my fix feature works

### CODE REVIEW

**Review by lumtis — COMMENTED** [review]
It seems that the test failures are related to the change @ws4charlie

**Review by kevinssgh — APPROVED** [review]
Looks good. I think it might be difficult to unit test some of these go routines and loops. Should probably look into making this easier later on.

**Comment by lumtis** [comment]
> Looks good. I think it might be difficult to unit test some of these go routines and loops. Should probably look into making this easier later on.

Yes, `startCctxScheduler` should definitely be simplified

**Comment by ws4charlie** [comment]
The diff view of this PR was somehow messed up. So I re-created the PR as https://github.com/zeta-chain/node/pull/1984

**Pull request closed without merging**
