### PR TITLE
chore: prepare zetaclient v22.1.0

### PR DESCRIPTION
**Pull request by gartnera**
Prepare v22.1.0 release which includes zetaclient TSS updates. This PR should be merged.

- https://github.com/zeta-chain/node/pull/3028
- https://github.com/zeta-chain/node/pull/3041
- https://github.com/zeta-chain/node/pull/3162

### CODE REVIEW

**Review by swift1337 — APPROVED** [review]

**Review by lumtis — APPROVED** [review]
LGTM as these are backported approved PR

**Review by brewmaster012 — APPROVED** [review]

**Comment by CryptoFewka** [comment]
@gartnera is it acceptable to cherry pick the two commits from https://github.com/zeta-chain/node/pull/3161  to this branch?

**Comment by gartnera** [comment]
> @gartnera is it acceptable to cherry pick the two commits from #3161 to this branch?

#3161 is still WIP. Once we have a final version yes.

**Comment by CryptoFewka** [comment]
I see @ws4charlie 's work on https://github.com/zeta-chain/node/pull/3162 replacing https://github.com/zeta-chain/node/pull/3161.

**Pull request merged**
