### PR TITLE
refactor: add more extensive check for reverted contract

### PR DESCRIPTION
**Pull request by lumtis**
# Description

Right now, to check if a contract is reverted, we check if the returned `res.Failed() == true`.
There can be situation where when `CallEVM` fail, the returned `res` will be `nil` and the error with contain the description `execution reverted`.
Since `depositAndCall` logic could be updated in the future and create a situation where `res` could become `nil` after reverted execution, this PR adds a more extensive check for the contract reverted taking this situation into account.

The PR also add more smoke test to test `DepositAndCall` with ethers.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Include instructions and any relevant details so others can reproduce. 

- [ ] Tested CCTX in localnet
- [ ] Tested in development environment
- [ ] Go unit tests
- [ ] Go integration tests
- [ ] Tested via GitHub Actions 

# Checklist:

- [ ] I have added unit tests that prove my fix feature works

### CODE REVIEW

**Comment by brewmaster012** [comment]
i vaguely remember this patch might be already incorporated in another PR, is that right? @lumtis

**Comment by lumtis** [comment]
> i vaguely remember this patch might be already incorporated in another PR, is that right? @lumtis

This PR is the result of the initial investigation I had on Denis' non-reverted cctx issue. I realize that the check for reverted tx we have doesn't handle all cases (the tx might revert and the check doesn't detect). It doesn't fix a current issue we have in the node right now (always detect reverted) but it might become an issue if we change the `DepositAndCall` logic in the future

**Comment by lumtis** [comment]
Fix for https://github.com/zeta-chain/node/issues/1347 : https://github.com/zeta-chain/node/pull/1214/commits/b3af0bdf41c86ea6ff247e96fe3d5d10f521b7cc

**Review by ws4charlie — APPROVED** [review]
looks good

**Review by brewmaster012 — COMMENTED** [review]
~Does this PR address this issue? #1347~
OK saw your previous comment. Is it possible to test the error message (evm reverted: ret 0x???) in the smoketest?

**Comment by lumtis** [comment]
> Alternatively, if the mocks in unit tests can simulate a remote contract call and result then that'll be great too.

I have one unit test here that calls a reverted function:
https://github.com/zeta-chain/node/blob/9a7a7812fef15198f57934fb9b337c19fe1e7a89/x/fungible/keeper/evm_test.go#L358

If we already have the smoke test calling a reverted function, I can add an assert in the smoke test

**Comment by lumtis** [comment]
@brewmaster012 added check in the smoke test
[0b2f828](https://github.com/zeta-chain/node/pull/1214/commits/0b2f828a9b38d58afa051fffd70ffa627c7a7ae1)
[9735294](https://github.com/zeta-chain/node/pull/1214/commits/9735294bfea5c7aa3d1c860e955f8f793dedec9d)

**Review by brewmaster012 — APPROVED** [review]
LGTM!

**Pull request merged**
