### PR TITLE
fix: updated publish-release and rc-release and added changelog change check

### PR DESCRIPTION
**Pull request by gzukel**
# Description

1. Added change-log-check.yml a PR check that ensures changelog.md has changed between PRs. Developers must add their changes to changelog.md before merging a PR.
2. Modified publish-release to follow GitOps. Now you must merge to the main branch with a the PR title that matches the version you are releasing with pattern vx.x.x.
3. Added hotfix ability to the publish-release pipeline where you can execute manually against any branch and generate a hotfix release.
4. Modified rc-release to trigger when tags are pushed to a branch that matches pattern: vx.x.x-rc.
5. Added changelog.md from the recent 10.0 releases

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

I tested this in our internal fork of the node repo for CI testing.

- [ ] Tested CCTX in localnet
- [ ] Tested in development environment
- [ ] Go unit tests
- [ ] Go integration tests
- [x] Tested via GitHub Actions 

# Checklist:

- [x] I have added unit tests that prove my fix feature works

### CODE REVIEW

**Comment by lumtis** [comment]
Could we also think about check if a label `no-changelog` is attached to the PR then the changelog check is not performed (in case of minimal change)

**Review by lumtis — COMMENTED** [review]
Could we also think about check if a label `no-changelog` is attached to the PR then the changelog check is not performed (in case of minimal change)

**Comment by lumtis** [comment]
Would call the PR more like `ci` than `fix`

**Review by lumtis — APPROVED** [review]
LGTM

**Review by CharlieMc0 — APPROVED** [review]

**Pull request merged**
