### PR TITLE
refactor(`crosschain`): rename `ZetaMinted` into `ValueReceived` in `MsgVoteOnObservedOutboundTx`

### PR DESCRIPTION
**Pull request by lumtis**
# Description

Rename `ZetaMinted` into `ValueReceived` to prevent confusion as this field means the value received from the outbound, gas for an external chain

Closes: https://github.com/zeta-chain/node/issues/1070

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Include instructions and any relevant details so others can reproduce. 

- [ ] Tested CCTX in localnet
- [ ] Tested in development environment
- [ ] Go unit tests
- [ ] Go integration tests
- [ ] Tested via GitHub Actions 

# Checklist:

- [ ] I have added unit tests that prove my fix feature works

### CODE REVIEW

**Review by brewmaster012 — COMMENTED** [review]
My understanding is that renaming protobuf field is backward compatible as long as the field number is maintained? 

So the only impact would be consumers of the REST API?

**Comment by lumtis** [comment]
Yes, we keep the same type and field number so it must be fine. I can check it manually.

**Review by kingpinXD — APPROVED** [review]

**Review by brewmaster012 — APPROVED** [review]

**Comment by brewmaster012** [comment]
cc @Mfigueira @GMaiolo @lucas-janon 
might affect RPC endpoint names/fields

**Comment by lumtis** [comment]
> > cc @Mfigueira @GMaiolo @lucas-janon might affect RPC endpoint names/fields
> 
> @brewmaster012 thanks for pinging! I don't see any place where we're using `ZetaMinted` in any app, so we should be fine as far as I see 👍

Thanks for the answer @GMaiolo! Could you tell also if https://github.com/zeta-chain/node/pull/1106 might create some problem on the app level?
We basically removing some namespaces from the rpc, described in the PR

**Comment by GMaiolo** [comment]
> > > cc @Mfigueira @GMaiolo @lucas-janon might affect RPC endpoint names/fields
> > 
> > 
> > @brewmaster012 thanks for pinging! I don't see any place where we're using `ZetaMinted` in any app, so we should be fine as far as I see 👍
> 
> Thanks for the answer @GMaiolo! Could you tell also if #1106 might create some problem on the app level? We basically removing some namespaces from the rpc, described in the PR

@lumtis will check later today!

**Comment by lumtis** [comment]
> @lumtis will check later today!

Thanks, not urgent

**Pull request merged**
